package org.redtreasure.preppy.ui.theme

import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable


// This is a placeholder. You should have this file generated by the KMP Wizard.
@Composable
fun PreppyTheme(content: @Composable () -> Unit) {
    MaterialTheme {
        content()
    }
}